In [1]:
import pandas as pd
import numpy as np

In [ ]:

df_raw = pd.read_csv("metadata.csv")

# GOLDEN RULE — Make a Copy!
df = df_raw.copy()

In [3]:
df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,...,NaN,NEV,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,PAT_1516_1765_530.png,False
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,PAT_46_881_939.png,True
2,PAT_1545,1867,NaN,NaN,NaN,NaN,77,NaN,NaN,NaN,...,NaN,ACK,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,PAT_1545_1867_547.png,False
3,PAT_1989,4061,NaN,NaN,NaN,NaN,75,NaN,NaN,NaN,...,NaN,ACK,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,PAT_1989_4061_934.png,False
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,PAT_684_1302_588.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2293,PAT_1708,3156,NaN,NaN,NaN,NaN,73,NaN,NaN,NaN,...,NaN,ACK,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,PAT_1708_3156_175.png,False
2294,PAT_46,880,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,12.0,BCC,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,PAT_46_880_140.png,True
2295,PAT_1343,1217,NaN,NaN,NaN,NaN,74,NaN,NaN,NaN,...,NaN,SEK,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,PAT_1343_1217_404.png,False
2296,PAT_326,690,False,False,POMERANIA,POMERANIA,58,True,FEMALE,True,...,4.0,BCC,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,PAT_326_690_823.png,True
2297,PAT_1714,3189,NaN,NaN,NaN,NaN,41,NaN,NaN,NaN,...,NaN,SEK,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,PAT_1714_3189_989.png,False

In [4]:
print(df.shape)

(2298, 26)

In [5]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2298 entries, 0 to 2297
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           2298 non-null   str
 1   lesion_id            2298 non-null   int64
 2   smoke                1494 non-null   object
 3   drink                1494 non-null   object
 4   background_father    1480 non-null   str
 5   background_mother    1476 non-null   str
 6   age                  2298 non-null   int64
 7   pesticide            1494 non-null   object
 8   gender               1494 non-null   str
 9   skin_cancer_history  1494 non-null   object
 10  cancer_history       1494 non-null   object
 11  has_piped_water      1494 non-null   object
 12  has_sewage_system    1494 non-null   object
 13  fitspatrick          1494 non-null   float64
 14  region               2298 non-null   str
 15  diameter_1           1494 non-null   float64
 16  diameter_2           1494 non-null   float64
 17  diagnostic           2298 non-null   str
 18  itch                 2298 non-null   str
 19  grew                 2298 non-null   str
 20  hurt                 2298 non-null   str
 21  changed              2298 non-null   str
 22  bleed                2298 non-null   str
 23  elevation            2298 non-null   str
 24  img_id               2298 non-null   str
 25  biopsed              2298 non-null   bool
dtypes: bool(1), float64(3), int64(2), object(7), str(13)
memory usage: 451.2+ KB
None

In [ ]:
# Check the datatypes

print(df.dtypes)

patient_id                 str
lesion_id                int64
smoke                   object
drink                   object
background_father          str
background_mother          str
age                      int64
pesticide               object
gender                     str
skin_cancer_history     object
cancer_history          object
has_piped_water         object
has_sewage_system       object
fitspatrick            float64
region                     str
diameter_1             float64
diameter_2             float64
diagnostic                 str
itch                       str
grew                       str
hurt                       str
changed                    str
bleed                      str
elevation                  str
img_id                     str
biopsed                   bool
dtype: object

In [7]:
print(df.head(10))

  patient_id  lesion_id  smoke  drink background_father background_mother  \
0   PAT_1516       1765    NaN    NaN               NaN               NaN
1     PAT_46        881  False  False         POMERANIA         POMERANIA
2   PAT_1545       1867    NaN    NaN               NaN               NaN
3   PAT_1989       4061    NaN    NaN               NaN               NaN
4    PAT_684       1302  False   True         POMERANIA         POMERANIA
5   PAT_1549       1882    NaN    NaN               NaN               NaN
6    PAT_778       1471  False   True           GERMANY             ITALY
7    PAT_117        179  False  False         POMERANIA         POMERANIA
8   PAT_1995       4080    NaN    NaN               NaN               NaN
9    PAT_705       4015  False   True           GERMANY           GERMANY

   age pesticide  gender skin_cancer_history  ... diameter_2 diagnostic  \
0    8       NaN     NaN                 NaN  ...        NaN        NEV
1   55     False  FEMALE                True  ...        5.0        BCC
2   77       NaN     NaN                 NaN  ...        NaN        ACK
3   75       NaN     NaN                 NaN  ...        NaN        ACK
4   79     False    MALE                True  ...        5.0        BCC
5   53       NaN     NaN                 NaN  ...        NaN        SEK
6   52     False  FEMALE               False  ...       10.0        BCC
7   74      True  FEMALE               False  ...       10.0        BCC
8   68       NaN     NaN                 NaN  ...        NaN        ACK
9   58      True  FEMALE                True  ...        7.0        ACK

    itch   grew   hurt  changed  bleed elevation                 img_id  \
0  FALSE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1516_1765_530.png
1   TRUE   TRUE  FALSE     TRUE   TRUE      TRUE     PAT_46_881_939.png
2   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1545_1867_547.png
3   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1989_4061_934.png
4   TRUE   TRUE  FALSE    FALSE   TRUE      TRUE   PAT_684_1302_588.png
5   TRUE  FALSE  FALSE    FALSE  FALSE      TRUE  PAT_1549_1882_230.png
6  FALSE   TRUE  FALSE     TRUE   TRUE      TRUE   PAT_778_1471_835.png
7   TRUE   TRUE   TRUE    FALSE   TRUE      TRUE    PAT_117_179_983.png
8   TRUE  FALSE  FALSE     TRUE  FALSE     FALSE  PAT_1995_4080_695.png
9  FALSE   TRUE  FALSE    FALSE  FALSE     FALSE   PAT_705_4015_413.png

  biopsed
0   False
1    True
2   False
3   False
4    True
5   False
6    True
7    True
8   False
9   False

[10 rows x 26 columns]

In [8]:
print(df.tail(10))

     patient_id  lesion_id  smoke  drink background_father background_mother  \
2288   PAT_1407       1402    NaN    NaN               NaN               NaN
2289    PAT_386        785   True  False         POMERANIA         POMERANIA
2290   PAT_1294       1031    NaN    NaN               NaN               NaN
2291    PAT_273        421  False  False         POMERANIA         POMERANIA
2292    PAT_491        934  False  False         POMERANIA         POMERANIA
2293   PAT_1708       3156    NaN    NaN               NaN               NaN
2294     PAT_46        880  False  False         POMERANIA         POMERANIA
2295   PAT_1343       1217    NaN    NaN               NaN               NaN
2296    PAT_326        690  False  False         POMERANIA         POMERANIA
2297   PAT_1714       3189    NaN    NaN               NaN               NaN

      age pesticide  gender skin_cancer_history  ... diameter_2 diagnostic  \
2288   81       NaN     NaN                 NaN  ...        NaN        ACK
2289   66     False    MALE                True  ...       15.0        ACK
2290   35       NaN     NaN                 NaN  ...        NaN        ACK
2291   41      True    MALE               False  ...        5.0        BCC
2292   43      True  FEMALE                True  ...        5.0        SCC
2293   73       NaN     NaN                 NaN  ...        NaN        ACK
2294   55     False  FEMALE                True  ...       12.0        BCC
2295   74       NaN     NaN                 NaN  ...        NaN        SEK
2296   58      True  FEMALE                True  ...        4.0        BCC
2297   41       NaN     NaN                 NaN  ...        NaN        SEK

       itch   grew   hurt  changed  bleed elevation                 img_id  \
2288   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1407_1402_562.png
2289   TRUE  FALSE   TRUE    FALSE   TRUE      TRUE    PAT_386_785_536.png
2290   TRUE  FALSE   TRUE    FALSE  FALSE     FALSE  PAT_1294_1031_466.png
2291   TRUE    UNK   TRUE      UNK   TRUE      TRUE    PAT_273_421_905.png
2292   TRUE    UNK  FALSE      UNK   TRUE      TRUE     PAT_491_934_46.png
2293   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1708_3156_175.png
2294   TRUE   TRUE  FALSE     TRUE  FALSE     FALSE     PAT_46_880_140.png
2295  FALSE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1343_1217_404.png
2296   TRUE  FALSE  FALSE    FALSE  FALSE      TRUE    PAT_326_690_823.png
2297  FALSE   TRUE  FALSE    FALSE  FALSE      TRUE  PAT_1714_3189_989.png

     biopsed
2288   False
2289    True
2290   False
2291    True
2292    True
2293   False
2294    True
2295   False
2296    True
2297   False

[10 rows x 26 columns]

In [ ]:
# Examine a random subset of rows to understand the structure and quality of the data.
print(df.sample(10))

     patient_id  lesion_id  smoke  drink background_father background_mother  \
1109    PAT_928       1764  False  False         POMERANIA         POMERANIA
1403     PAT_99        153  False  False         POMERANIA         POMERANIA
2233   PAT_1967       3976    NaN    NaN               NaN               NaN
969     PAT_409       2614  False  False             ITALY             ITALY
1158   PAT_1486       1684    NaN    NaN               NaN               NaN
536     PAT_822       1550  False  False               UNK               UNK
335     PAT_522        986  False  False             ITALY             ITALY
643     PAT_412        817  False  False         POMERANIA         POMERANIA
1301   PAT_1946       3924    NaN    NaN               NaN               NaN
653    PAT_2106       4590    NaN    NaN               NaN               NaN

      age pesticide  gender skin_cancer_history  ... diameter_2 diagnostic  \
1109   64      True  FEMALE               False  ...        5.0        BCC
1403   78     False  FEMALE               False  ...        6.0        BCC
2233   75       NaN     NaN                 NaN  ...        NaN        ACK
969    46      True  FEMALE               False  ...        3.0        ACK
1158   73       NaN     NaN                 NaN  ...        NaN        ACK
536    72     False    MALE               False  ...       10.0        BCC
335    53     False    MALE               False  ...        8.0        BCC
643    46      True    MALE               False  ...        9.0        BCC
1301   73       NaN     NaN                 NaN  ...        NaN        SEK
653    60       NaN     NaN                 NaN  ...        NaN        ACK

       itch   grew   hurt  changed  bleed elevation                 img_id  \
1109  FALSE    UNK  FALSE      UNK  FALSE      TRUE   PAT_928_1764_426.png
1403   TRUE   TRUE   TRUE    FALSE   TRUE      TRUE     PAT_99_153_636.png
2233   TRUE  FALSE  FALSE    FALSE   TRUE     FALSE  PAT_1967_3976_736.png
969    TRUE  FALSE  FALSE    FALSE  FALSE     FALSE   PAT_409_2614_805.png
1158   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1486_1684_182.png
536    TRUE   TRUE  FALSE    FALSE  FALSE      TRUE   PAT_822_1550_826.png
335    TRUE   TRUE   TRUE    FALSE   TRUE      TRUE    PAT_522_986_305.png
643   FALSE   TRUE  FALSE    FALSE  FALSE      TRUE    PAT_412_817_232.png
1301   TRUE   TRUE  FALSE    FALSE  FALSE      TRUE   PAT_1946_3924_24.png
653   FALSE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_2106_4590_227.png

     biopsed
1109    True
1403    True
2233   False
969    False
1158   False
536     True
335     True
643     True
1301   False
653    False

[10 rows x 26 columns]

In [10]:
print(df.isna().sum())

patient_id               0
lesion_id                0
smoke                  804
drink                  804
background_father      818
background_mother      822
age                      0
pesticide              804
gender                 804
skin_cancer_history    804
cancer_history         804
has_piped_water        804
has_sewage_system      804
fitspatrick            804
region                   0
diameter_1             804
diameter_2             804
diagnostic               0
itch                     0
grew                     0
hurt                     0
changed                  0
bleed                    0
elevation                0
img_id                   0
biopsed                  0
dtype: int64

In [11]:
print(len(df))
print(df['smoke'].isna().sum())

print(df['drink'].isna().sum())

2298
804
804

In [ ]:
# checking messy data in both the columns

print(df['biopsed'].unique())
print()
print(df['diagnostic'].unique())

[False  True]

<StringArray>
['NEV', 'BCC', 'ACK', 'SEK', 'SCC', 'MEL']
Length: 6, dtype: str

In [13]:
print(df[df['biopsed']==False]['diagnostic'].value_counts())
print()
print(df[df['biopsed']==True]['diagnostic'].value_counts())

diagnostic
ACK    552
SEK    220
NEV    184
Name: count, dtype: int64

diagnostic
BCC    845
SCC    192
ACK    178
NEV     60
MEL     52
SEK     15
Name: count, dtype: int64

In [ ]:

# Biopsed=False wale patients ke symptoms

print("Biopsed = FALSE wale symptoms:")
print(df[df['biopsed']==False][['itch','grew','hurt','changed','bleed','elevation']].value_counts().head(5))

print()

# Biopsed=True wale patients ke symptoms  
print("Biopsed = TRUE wale symptoms:")
print(df[df['biopsed']==True][['itch','grew','hurt','changed','bleed','elevation']].value_counts().head(5))

Biopsed = FALSE wale symptoms:
itch   grew   hurt   changed  bleed  elevation
TRUE   FALSE  FALSE  FALSE    FALSE  FALSE        275
FALSE  TRUE   FALSE  FALSE    FALSE  TRUE         151
       FALSE  FALSE  FALSE    FALSE  FALSE        126
                                     TRUE         109
TRUE   FALSE  FALSE  FALSE    FALSE  TRUE          76
Name: count, dtype: int64

Biopsed = TRUE wale symptoms:
itch   grew  hurt   changed  bleed  elevation
TRUE   TRUE  TRUE   FALSE    TRUE   TRUE         131
       UNK   FALSE  UNK      FALSE  TRUE          95
       TRUE  FALSE  FALSE    TRUE   TRUE          87
FALSE  UNK   FALSE  UNK      FALSE  TRUE          82
TRUE   TRUE  FALSE  FALSE    FALSE  TRUE          82
Name: count, dtype: int64

Strategy Pehle, Code Baad Mein!
Ek Data Analyst kabhi bhi randomly columns fill nahi karta.
Pehle har column ka nature samajhta hai, phir decide karta hai strategy.

Columns Ko Groups Mein Socho
Dataset ke saare missing columns ko 3 buckets mein daalo:
Bucket 1 — Numbers 🔢
diameter_1, diameter_2

Bucket 2 — Haan/Nahi wale ✅❌
smoke, drink, pesticide, skin_cancer_history, cancer_history, has_piped_water, has_sewage_system

Bucket 3 — Categories 🏷️
gender, fitspatrick, background_father, background_mother

In [15]:
print(df[['diameter_1', 'diameter_2']].describe())
print()
print(df[['diameter_1', 'diameter_2']].corr())

        diameter_1   diameter_2
count  1494.000000  1494.000000
mean     11.897055     8.852209
std       8.634492     5.797036
min       0.000000     0.000000
25%       7.000000     5.000000
50%      10.000000     8.000000
75%      15.000000    10.000000
max     100.000000    70.000000

            diameter_1  diameter_2
diameter_1    1.000000    0.858215
diameter_2    0.858215    1.000000

In [16]:
overall = df['diameter_1'].mean()
false_mean = df[df['biopsed']==False]['diameter_1'].mean()
true_mean = df[df['biopsed']==True]['diameter_1'].mean()

print(f"Overall average: {overall:.2f}")
print(f"Biopsed=False average: {false_mean:.2f}")
print(f"Biopsed=True average: {true_mean:.2f}")

Overall average: 11.90
Biopsed=False average: 10.40
Biopsed=True average: 12.07

In [17]:
ack_false = df[(df['biopsed']==False) & (df['diagnostic']=='ACK')]   # 552 rows * 26 columns
ack_true  = df[(df['biopsed']==True)  & (df['diagnostic']=='ACK')]   # 178 rows * 26 columns

#print(ack_false)
#print(f"_______________________________")
#print(ack_true)
#print(f"_______________________________")


print("ACK + Biopsed=False ka average size:")
print(ack_false[['diameter_1','diameter_2']].mean())

print()
print("ACK + Biopsed=True ka average size:")
print(ack_true[['diameter_1','diameter_2']].mean())

print()
print("ACK + Biopsed=False mein bleed=True kitne?")
print(ack_false['bleed'].value_counts())

print()
print("ACK + Biopsed=True mein bleed=True kitne?")
print(ack_true['bleed'].value_counts())

ACK + Biopsed=False ka average size:
diameter_1    10.828571
diameter_2     7.580952
dtype: float64

ACK + Biopsed=True ka average size:
diameter_1    11.067416
diameter_2     8.544944
dtype: float64

ACK + Biopsed=False mein bleed=True kitne?
bleed
FALSE    500
TRUE      52
Name: count, dtype: int64

ACK + Biopsed=True mein bleed=True kitne?
bleed
FALSE    141
TRUE      37
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2298 entries, 0 to 2297
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           2298 non-null   str
 1   lesion_id            2298 non-null   int64
 2   smoke                1494 non-null   object
 3   drink                1494 non-null   object
 4   background_father    1480 non-null   str
 5   background_mother    1476 non-null   str
 6   age                  2298 non-null   int64
 7   pesticide            1494 non-null   object
 8   gender               1494 non-null   str
 9   skin_cancer_history  1494 non-null   object
 10  cancer_history       1494 non-null   object
 11  has_piped_water      1494 non-null   object
 12  has_sewage_system    1494 non-null   object
 13  fitspatrick          1494 non-null   float64
 14  region               2298 non-null   str
 15  diameter_1           1494 non-null   float64
 16  diameter_2           1494 non-null   float64
 17  diagnostic           2298 non-null   str
 18  itch                 2298 non-null   str
 19  grew                 2298 non-null   str
 20  hurt                 2298 non-null   str
 21  changed              2298 non-null   str
 22  bleed                2298 non-null   str
 23  elevation            2298 non-null   str
 24  img_id               2298 non-null   str
 25  biopsed              2298 non-null   bool
dtypes: bool(1), float64(3), int64(2), object(7), str(13)
memory usage: 451.2+ KB

In [19]:


print("=== Biopsed=TRUE mein missing values ===")
true_df = df[df['biopsed']==True]
print(true_df)    # 1342 rows * 26 columns
print('__________________________________________')
print(true_df.isnull().sum())

print('*********************************************')

print()
print("=== Biopsed=FALSE mein missing values ===")
false_df = df[df['biopsed']==False]
print(false_df)    # 956 rows * 26 columns
print('__________________________________________')
print(false_df.isnull().sum())

=== Biopsed=TRUE mein missing values ===
     patient_id  lesion_id  smoke  drink background_father background_mother  \
1        PAT_46        881  False  False         POMERANIA         POMERANIA
4       PAT_684       1302  False   True         POMERANIA         POMERANIA
6       PAT_778       1471  False   True           GERMANY             ITALY
7       PAT_117        179  False  False         POMERANIA         POMERANIA
11      PAT_967       1827  False  False         POMERANIA         POMERANIA
...         ...        ...    ...    ...               ...               ...
2289    PAT_386        785   True  False         POMERANIA         POMERANIA
2291    PAT_273        421  False  False         POMERANIA         POMERANIA
2292    PAT_491        934  False  False         POMERANIA         POMERANIA
2294     PAT_46        880  False  False         POMERANIA         POMERANIA
2296    PAT_326        690  False  False         POMERANIA         POMERANIA

      age pesticide  gender skin_cancer_history  ... diameter_2 diagnostic  \
1      55     False  FEMALE                True  ...        5.0        BCC
4      79     False    MALE                True  ...        5.0        BCC
6      52     False  FEMALE               False  ...       10.0        BCC
7      74      True  FEMALE               False  ...       10.0        BCC
11     34      True  FEMALE                True  ...        4.0        BCC
...   ...       ...     ...                 ...  ...        ...        ...
2289   66     False    MALE                True  ...       15.0        ACK
2291   41      True    MALE               False  ...        5.0        BCC
2292   43      True  FEMALE                True  ...        5.0        SCC
2294   55     False  FEMALE                True  ...       12.0        BCC
2296   58      True  FEMALE                True  ...        4.0        BCC

       itch   grew   hurt  changed  bleed elevation                img_id  \
1      TRUE   TRUE  FALSE     TRUE   TRUE      TRUE    PAT_46_881_939.png
4      TRUE   TRUE  FALSE    FALSE   TRUE      TRUE  PAT_684_1302_588.png
6     FALSE   TRUE  FALSE     TRUE   TRUE      TRUE  PAT_778_1471_835.png
7      TRUE   TRUE   TRUE    FALSE   TRUE      TRUE   PAT_117_179_983.png
11     TRUE    UNK  FALSE      UNK   TRUE      TRUE  PAT_967_1827_247.png
...     ...    ...    ...      ...    ...       ...                   ...
2289   TRUE  FALSE   TRUE    FALSE   TRUE      TRUE   PAT_386_785_536.png
2291   TRUE    UNK   TRUE      UNK   TRUE      TRUE   PAT_273_421_905.png
2292   TRUE    UNK  FALSE      UNK   TRUE      TRUE    PAT_491_934_46.png
2294   TRUE   TRUE  FALSE     TRUE  FALSE     FALSE    PAT_46_880_140.png
2296   TRUE  FALSE  FALSE    FALSE  FALSE      TRUE   PAT_326_690_823.png

     biopsed
1       True
4       True
6       True
7       True
11      True
...      ...
2289    True
2291    True
2292    True
2294    True
2296    True

[1342 rows x 26 columns]
__________________________________________
patient_id             0
lesion_id              0
smoke                  0
drink                  0
background_father      0
background_mother      0
age                    0
pesticide              0
gender                 0
skin_cancer_history    0
cancer_history         0
has_piped_water        0
has_sewage_system      0
fitspatrick            0
region                 0
diameter_1             0
diameter_2             0
diagnostic             0
itch                   0
grew                   0
hurt                   0
changed                0
bleed                  0
elevation              0
img_id                 0
biopsed                0
dtype: int64
*********************************************

=== Biopsed=FALSE mein missing values ===
     patient_id  lesion_id smoke drink background_father background_mother  \
0      PAT_1516       1765   NaN   NaN               NaN               NaN
2      PAT_1545       1867   NaN   NaN               NaN               NaN
3      PAT_1989       4061   NaN   NaN               NaN               NaN
5      PAT_1549       1882   NaN   NaN               NaN               NaN
8      PAT_1995       4080   NaN   NaN               NaN               NaN
...         ...        ...   ...   ...               ...               ...
2288   PAT_1407       1402   NaN   NaN               NaN               NaN
2290   PAT_1294       1031   NaN   NaN               NaN               NaN
2293   PAT_1708       3156   NaN   NaN               NaN               NaN
2295   PAT_1343       1217   NaN   NaN               NaN               NaN
2297   PAT_1714       3189   NaN   NaN               NaN               NaN

      age pesticide gender skin_cancer_history  ... diameter_2 diagnostic  \
0       8       NaN    NaN                 NaN  ...        NaN        NEV
2      77       NaN    NaN                 NaN  ...        NaN        ACK
3      75       NaN    NaN                 NaN  ...        NaN        ACK
5      53       NaN    NaN                 NaN  ...        NaN        SEK
8      68       NaN    NaN                 NaN  ...        NaN        ACK
...   ...       ...    ...                 ...  ...        ...        ...
2288   81       NaN    NaN                 NaN  ...        NaN        ACK
2290   35       NaN    NaN                 NaN  ...        NaN        ACK
2293   73       NaN    NaN                 NaN  ...        NaN        ACK
2295   74       NaN    NaN                 NaN  ...        NaN        SEK
2297   41       NaN    NaN                 NaN  ...        NaN        SEK

       itch   grew   hurt  changed  bleed elevation                 img_id  \
0     FALSE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1516_1765_530.png
2      TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1545_1867_547.png
3      TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1989_4061_934.png
5      TRUE  FALSE  FALSE    FALSE  FALSE      TRUE  PAT_1549_1882_230.png
8      TRUE  FALSE  FALSE     TRUE  FALSE     FALSE  PAT_1995_4080_695.png
...     ...    ...    ...      ...    ...       ...                    ...
2288   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1407_1402_562.png
2290   TRUE  FALSE   TRUE    FALSE  FALSE     FALSE  PAT_1294_1031_466.png
2293   TRUE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1708_3156_175.png
2295  FALSE  FALSE  FALSE    FALSE  FALSE     FALSE  PAT_1343_1217_404.png
2297  FALSE   TRUE  FALSE    FALSE  FALSE      TRUE  PAT_1714_3189_989.png

     biopsed
0      False
2      False
3      False
5      False
8      False
...      ...
2288   False
2290   False
2293   False
2295   False
2297   False

[956 rows x 26 columns]
__________________________________________
patient_id               0
lesion_id                0
smoke                  804
drink                  804
background_father      818
background_mother      822
age                      0
pesticide              804
gender                 804
skin_cancer_history    804
cancer_history         804
has_piped_water        804
has_sewage_system      804
fitspatrick            804
region                   0
diameter_1             804
diameter_2             804
diagnostic               0
itch                     0
grew                     0
hurt                     0
changed                  0
bleed                    0
elevation                0
img_id                   0
biopsed                  0
dtype: int64

In [20]:
biopsed_false_mask = df['biopsed'] == False

# diameter_1 fill karo
false_d1_mean = df[biopsed_false_mask]['diameter_1'].mean()

df.loc[
    biopsed_false_mask & df['diameter_1'].isnull(),
    'diameter_1'
] = false_d1_mean


biopsed_false_mask = df['biopsed'] == False

# diameter_2 fill karo
false_d2_mean = df[biopsed_false_mask]['diameter_2'].mean()

df.loc[
    biopsed_false_mask & df['diameter_2'].isnull(),
    'diameter_2'
] = false_d2_mean

In [21]:
print(df[biopsed_false_mask]['diameter_1'].isnull().sum())
print(df[biopsed_false_mask]['diameter_2'].isnull().sum())

0
0

# smoke ka example
df['smoke'] = df['smoke'].fillna('Unknown')

df[['drink', 'pesticide']] = df[['drink', 'pesticide']] (Ye dono columns ka mini-dataframe return karta hai.).fillna('Unknown')

In [22]:
# df['smoke'] = df['smoke'].fillna('Unknown')

cols = ['smoke' , 'drink', 'pesticide' , 'skin_cancer_history' , 'cancer_history', 'has_piped_water', 'has_sewage_system']

df[cols] = df[cols].fillna('Unknown')

In [23]:
print(df['smoke'].isnull().sum())
print(df['pesticide'].isnull().sum())

0
0

`gender`, `fitspatrick`, `background_father`, `background_mother -- `Inhe bhi Unknown fill karna sahi hoga, kyunki 
hum sach mei nahi pata inka data, assume nahi kar sakte. lekin fitspatrick numerical column hai.

In [24]:
cols_1 = ['gender' , 'background_father', 'background_mother']

df[cols_1] = df[cols_1].fillna('Unknown')

In [25]:
fitspatrick_false_mask = df['biopsed'] == False

false_fitspatrick_mean = df[fitspatrick_false_mask]['fitspatrick'].mean()

df.loc[
    fitspatrick_false_mask & df['fitspatrick'].isnull(),
    'fitspatrick'
] = false_fitspatrick_mean

In [26]:
print(df['fitspatrick'].isnull().sum())

0

In [ ]:
# Verify the cleaning process.

print("=== Remaining NaN counts ===")
print(df.isnull().sum())

=== Remaining NaN counts ===
patient_id             0
lesion_id              0
smoke                  0
drink                  0
background_father      0
background_mother      0
age                    0
pesticide              0
gender                 0
skin_cancer_history    0
cancer_history         0
has_piped_water        0
has_sewage_system      0
fitspatrick            0
region                 0
diameter_1             0
diameter_2             0
diagnostic             0
itch                   0
grew                   0
hurt                   0
changed                0
bleed                  0
elevation              0
img_id                 0
biopsed                0
dtype: int64


TASK 1 COMPLETE! DATA CLEANING DONE!
Every column — 0 missing values!

In [ ]:
# Now saving the cleaned dataset.

df.to_csv('metadata_cleaned.csv', index=False)
print("Saved!")

Saved!

Task 2 :

"Multiple skin cancer — logically check karo — kisko future mein cancer ho sakta hai — high risk mein kaun hai?" How will I do it?

In [29]:
df['diameter_1'].min()
df['diameter_1'].max()

print(f"----------------------------")

df['diameter_2'].min()
df['diameter_2'].max()

----------------------------

np.float64(70.0)

Complete Risk Score Formula:
Column                 True           Unknown           False
grew                   1               0.5               0
changed                1                 0.5             0
bleed               1                    0.5               0
hurt                  1                  0.5                 0
elevation               1                 0.5                0
smoke              1                    0.5                0
cancer_history        1                0.5                   0
diameter_1 > 15       1                 —                    0
diameter_2 > 15        1                  —                    0


Maximum possible score = 9 points

Risk Categories
0 - 3  → Low Risk   🟢
3 - 6  → Medium Risk 🟡
6 - 9  → High Risk  🔴

In [31]:
risk_df = df[df['biopsed']==False].copy()

cols_2 = ['grew' , 'changed', 'bleed', 'hurt', 'elevation', 'smoke' , 'cancer_history']

risk_df[['score_grew' , 'score_changed', 'score_bleed' , 'score_hurt', 'score_elevation' , 'score_smoke', 'score_cancer_history']] = risk_df[cols_2].replace({
    True: 1, 
    False: 0,
    'Unknown':0.5
})

In [32]:
risk_df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,elevation,img_id,biopsed,score_grew,score_changed,score_bleed,score_hurt,score_elevation,score_smoke,score_cancer_history
0,PAT_1516,1765,Unknown,Unknown,Unknown,Unknown,8,Unknown,Unknown,Unknown,...,FALSE,PAT_1516_1765_530.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
2,PAT_1545,1867,Unknown,Unknown,Unknown,Unknown,77,Unknown,Unknown,Unknown,...,FALSE,PAT_1545_1867_547.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
3,PAT_1989,4061,Unknown,Unknown,Unknown,Unknown,75,Unknown,Unknown,Unknown,...,FALSE,PAT_1989_4061_934.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
5,PAT_1549,1882,Unknown,Unknown,Unknown,Unknown,53,Unknown,Unknown,Unknown,...,TRUE,PAT_1549_1882_230.png,False,FALSE,FALSE,FALSE,FALSE,TRUE,0.5,0.5
8,PAT_1995,4080,Unknown,Unknown,Unknown,Unknown,68,Unknown,Unknown,Unknown,...,FALSE,PAT_1995_4080_695.png,False,FALSE,TRUE,FALSE,FALSE,FALSE,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,PAT_1407,1402,Unknown,Unknown,Unknown,Unknown,81,Unknown,Unknown,Unknown,...,FALSE,PAT_1407_1402_562.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
2290,PAT_1294,1031,Unknown,Unknown,Unknown,Unknown,35,Unknown,Unknown,Unknown,...,FALSE,PAT_1294_1031_466.png,False,FALSE,FALSE,FALSE,TRUE,FALSE,0.5,0.5
2293,PAT_1708,3156,Unknown,Unknown,Unknown,Unknown,73,Unknown,Unknown,Unknown,...,FALSE,PAT_1708_3156_175.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
2295,PAT_1343,1217,Unknown,Unknown,Unknown,Unknown,74,Unknown,Unknown,Unknown,...,FALSE,PAT_1343_1217_404.png,False,FALSE,FALSE,FALSE,FALSE,FALSE,0.5,0.5
2297,PAT_1714,3189,Unknown,Unknown,Unknown,Unknown,41,Unknown,Unknown,Unknown,...,TRUE,PAT_1714_3189_989.png,False,TRUE,FALSE,FALSE,FALSE,TRUE,0.5,0.5

In [34]:
print(risk_df['grew'].dtype)
print(risk_df['grew'].unique())
print()
print(risk_df['smoke'].dtype)
print(risk_df['smoke'].unique())

str
<StringArray>
['FALSE', 'TRUE']
Length: 2, dtype: str

object
['Unknown' False True]

In [35]:
# cols_2 ke liye - grew, changed, bleed, hurt, elevation
# Yeh sab STRING hain - 'TRUE'/'FALSE' capital mein
cols_boolean = ['grew','changed','bleed','hurt','elevation']

risk_df[['score_grew','score_changed','score_bleed',
         'score_hurt','score_elevation']] = risk_df[cols_boolean].replace({
    'TRUE': 1,
    'FALSE': 0
})

# smoke aur cancer_history ke liye - mixed type hai
cols_mixed = ['smoke','cancer_history']

risk_df[['score_smoke','score_cancer_history']] = risk_df[cols_mixed].replace({
    True: 1,
    False: 0,
    'Unknown': 0.5
})

In [ ]:


risk_df = df[df['biopsed']==False].copy()

# Step 1a — grew, changed, bleed, hurt, elevation
# Yeh STRING hain — 'TRUE'/'FALSE' capital mein
cols_boolean = ['grew','changed','bleed','hurt','elevation']
risk_df[['score_grew','score_changed','score_bleed',
         'score_hurt','score_elevation']] = risk_df[cols_boolean].replace({
    'TRUE': 1,
    'FALSE': 0
})

# Step 1b — smoke aur cancer_history alag!
risk_df['score_smoke'] = risk_df['smoke'].replace({
    True: 1, False: 0, 'Unknown': 0.5
})
risk_df['score_cancer_history'] = risk_df['cancer_history'].replace({
    True: 1, False: 0, 'Unknown': 0.5
})

# Step 2 — Diameter
risk_df['score_diameter_1'] = (risk_df['diameter_1'] > 15).astype(int)
risk_df['score_diameter_2'] = (risk_df['diameter_2'] > 15).astype(int)

# Step 3 — Total score
risk_df['total_risk_score'] = risk_df[[
    'score_grew','score_changed','score_bleed',
    'score_hurt','score_elevation','score_smoke',
    'score_cancer_history','score_diameter_1','score_diameter_2'
]].sum(axis=1)

# Step 4 — Category
risk_df['risk_category'] = pd.cut(
    risk_df['total_risk_score'],
    #bins=[-0.1,3,6,9],
    bins=[-0.1, 2, 3.5, 5.1],
    labels=['Low Risk', 'Medium Risk', 'High Risk']
)

print(risk_df['risk_category'].value_counts())

risk_category
Low Risk       708
Medium Risk    224
High Risk       24
Name: count, dtype: int64

In [37]:
risk_df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,score_changed,score_bleed,score_hurt,score_elevation,score_smoke,score_cancer_history,score_diameter_1,score_diameter_2,total_risk_score,risk_category
0,PAT_1516,1765,Unknown,Unknown,Unknown,Unknown,8,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2,PAT_1545,1867,Unknown,Unknown,Unknown,Unknown,77,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
3,PAT_1989,4061,Unknown,Unknown,Unknown,Unknown,75,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
5,PAT_1549,1882,Unknown,Unknown,Unknown,Unknown,53,Unknown,Unknown,Unknown,...,0,0,0,1,0.5,0.5,0,0,2.0,Low Risk
8,PAT_1995,4080,Unknown,Unknown,Unknown,Unknown,68,Unknown,Unknown,Unknown,...,1,0,0,0,0.5,0.5,0,0,2.0,Low Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,PAT_1407,1402,Unknown,Unknown,Unknown,Unknown,81,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2290,PAT_1294,1031,Unknown,Unknown,Unknown,Unknown,35,Unknown,Unknown,Unknown,...,0,0,1,0,0.5,0.5,0,0,2.0,Low Risk
2293,PAT_1708,3156,Unknown,Unknown,Unknown,Unknown,73,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2295,PAT_1343,1217,Unknown,Unknown,Unknown,Unknown,74,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2297,PAT_1714,3189,Unknown,Unknown,Unknown,Unknown,41,Unknown,Unknown,Unknown,...,0,0,0,1,0.5,0.5,0,0,3.0,Medium Risk

In [ ]:
# High Risk = 0 suspicious.

# Verifying.

print("Max risk score:", risk_df['total_risk_score'].max())
print("Min risk score:", risk_df['total_risk_score'].min())
print()
print(risk_df['total_risk_score'].value_counts().sort_index(ascending=False).head(10))

Max risk score: 5.0
Min risk score: 0

total_risk_score
5.0      4
4.0     20
3.0    224
2.0    295
1.0    393
0       20
Name: count, dtype: int64

Adjusting the Bins:
Maximum score 5.0 hai — toh categories yeh honi chahiye:
0 - 2   → Low Risk    🟢
2 - 3.5 → Medium Risk 🟡
3.5 - 5 → High Risk   🔴

Ek Important Baat Samjho! 🧠

Bins fixed nahi hote — data dekh ke decide karte hain!

Pehle humne socha 0-9 scale hoga — lekin data ne bataya max 5 hai!

In [39]:
# Hamesha verify karo!
print("Total patients:", len(risk_df))
print("Categorized:", risk_df['risk_category'].value_counts().sum())

Total patients: 956
Categorized: 956

In [ ]:


high_risk = risk_df[risk_df['risk_category'] == 'High Risk']
print(high_risk)
print('________________________________________________')
print(high_risk[['patient_id','diagnostic','total_risk_score',
                 'grew','bleed','changed','smoke',
                 'cancer_history','diameter_1']].to_string())

     patient_id  lesion_id    smoke    drink background_father  \
34     PAT_1926       3871  Unknown  Unknown           Unknown
307    PAT_1682       3050  Unknown  Unknown           Unknown
490      PAT_87        133    False    False         POMERANIA
640    PAT_2131       4683  Unknown  Unknown           Unknown
651      PAT_61        299     True    False             ITALY
671    PAT_1914       3823  Unknown  Unknown           Unknown
672    PAT_1978       4004  Unknown  Unknown           Unknown
899    PAT_2103       4581  Unknown  Unknown           Unknown
1017   PAT_1951       3934  Unknown  Unknown           Unknown
1242   PAT_1351       1231  Unknown  Unknown           Unknown
1278   PAT_1153        555  Unknown  Unknown           Unknown
1405   PAT_1129        498  Unknown  Unknown           Unknown
1414   PAT_2022       4184  Unknown  Unknown           Unknown
1483    PAT_270       1384    False    False         POMERANIA
1527     PAT_87        133    False    False         POMERANIA
1532   PAT_1960       3957  Unknown  Unknown           Unknown
1557   PAT_1950       3932  Unknown  Unknown           Unknown
1629   PAT_2109       4598  Unknown  Unknown           Unknown
1638    PAT_877       4672    False     True           Unknown
1665    PAT_433       2650    False     True           GERMANY
1712     PAT_59         46     True    False            BRAZIL
1980   PAT_1928       3876  Unknown  Unknown           Unknown
2160     PAT_87        133    False    False         POMERANIA
2189   PAT_1978       4004  Unknown  Unknown           Unknown

     background_mother  age pesticide   gender skin_cancer_history  ...  \
34             Unknown   78   Unknown  Unknown             Unknown  ...
307            Unknown   48   Unknown  Unknown             Unknown  ...
490          POMERANIA   57     False   FEMALE                True  ...
640            Unknown   69   Unknown  Unknown             Unknown  ...
651              ITALY   50     False   FEMALE               False  ...
671            Unknown   56   Unknown  Unknown             Unknown  ...
672            Unknown   75   Unknown  Unknown             Unknown  ...
899            Unknown   18   Unknown  Unknown             Unknown  ...
1017           Unknown   79   Unknown  Unknown             Unknown  ...
1242           Unknown   25   Unknown  Unknown             Unknown  ...
1278           Unknown   32   Unknown  Unknown             Unknown  ...
1405           Unknown   51   Unknown  Unknown             Unknown  ...
1414           Unknown   55   Unknown  Unknown             Unknown  ...
1483         POMERANIA   90     False   FEMALE               False  ...
1527         POMERANIA   57     False   FEMALE                True  ...
1532           Unknown   34   Unknown  Unknown             Unknown  ...
1557           Unknown   68   Unknown  Unknown             Unknown  ...
1629           Unknown   55   Unknown  Unknown             Unknown  ...
1638           Unknown   62      True     MALE               False  ...
1665           GERMANY   30     False     MALE               False  ...
1712            BRAZIL   73     False   FEMALE               False  ...
1980           Unknown   37   Unknown  Unknown             Unknown  ...
2160         POMERANIA   57     False   FEMALE                True  ...
2189           Unknown   75   Unknown  Unknown             Unknown  ...

     score_changed score_bleed score_hurt  score_elevation score_smoke  \
34               1           0          1                1         0.5
307              1           0          0                1         0.5
490              0           0          0                1           0
640              1           0          0                1         0.5
651              0           0          0                1           1
671              0           1          0                1         0.5
672              1           1          0                1         0.5
899              1           0          0                1         0.5
1017             1           1          0                0         0.5
1242             1           0          0                1         0.5
1278             0           1          0                1         0.5
1405             0           0          1                1         0.5
1414             1           0          0                1         0.5
1483             0           1          1                1           0
1527             0           0          0                1           0
1532             1           0          1                1         0.5
1557             0           1          0                1         0.5
1629             1           0          0                1         0.5
1638             1           1          0                1           0
1665             0           0          0                1           0
1712             0           0          0                1           1
1980             1           0          0                1         0.5
2160             0           0          0                1           0
2189             1           1          0                1         0.5

      score_cancer_history  score_diameter_1 score_diameter_2  \
34                     0.5                 0                0
307                    0.5                 0                0
490                      1                 1                0
640                    0.5                 0                0
651                      1                 0                0
671                    0.5                 0                0
672                    0.5                 0                0
899                    0.5                 0                0
1017                   0.5                 0                0
1242                   0.5                 0                0
1278                   0.5                 0                0
1405                   0.5                 0                0
1414                   0.5                 0                0
1483                     1                 0                0
1527                     1                 1                0
1532                   0.5                 0                0
1557                   0.5                 0                0
1629                   0.5                 0                0
1638                     0                 0                0
1665                     1                 1                1
1712                     0                 1                0
1980                   0.5                 0                0
2160                     1                 1                0
2189                   0.5                 0                0

     total_risk_score risk_category
34                4.0     High Risk
307               4.0     High Risk
490                 4     High Risk
640               4.0     High Risk
651                 4     High Risk
671               4.0     High Risk
672               5.0     High Risk
899               4.0     High Risk
1017              4.0     High Risk
1242              4.0     High Risk
1278              4.0     High Risk
1405              4.0     High Risk
1414              4.0     High Risk
1483                4     High Risk
1527                4     High Risk
1532              5.0     High Risk
1557              4.0     High Risk
1629              4.0     High Risk
1638                4     High Risk
1665                5     High Risk
1712                4     High Risk
1980              4.0     High Risk
2160                4     High Risk
2189              5.0     High Risk

[24 rows x 37 columns]
________________________________________________
     patient_id diagnostic total_risk_score   grew  bleed changed    smoke cancer_history  diameter_1
34     PAT_1926        SEK              4.0  FALSE  FALSE    TRUE  Unknown        Unknown   10.401316
307    PAT_1682        SEK              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
490      PAT_87        SEK                4   TRUE  FALSE   FALSE    False           True   17.000000
640    PAT_2131        ACK              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
651      PAT_61        NEV                4   TRUE  FALSE   FALSE     True           True    5.000000
671    PAT_1914        NEV              4.0   TRUE   TRUE   FALSE  Unknown        Unknown   10.401316
672    PAT_1978        SEK              5.0   TRUE   TRUE    TRUE  Unknown        Unknown   10.401316
899    PAT_2103        NEV              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
1017   PAT_1951        ACK              4.0   TRUE   TRUE    TRUE  Unknown        Unknown   10.401316
1242   PAT_1351        NEV              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
1278   PAT_1153        NEV              4.0   TRUE   TRUE   FALSE  Unknown        Unknown   10.401316
1405   PAT_1129        NEV              4.0   TRUE  FALSE   FALSE  Unknown        Unknown   10.401316
1414   PAT_2022        ACK              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
1483    PAT_270        ACK                4  FALSE   TRUE   FALSE    False           True   13.000000
1527     PAT_87        SEK                4   TRUE  FALSE   FALSE    False           True   17.000000
1532   PAT_1960        NEV              5.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
1557   PAT_1950        ACK              4.0   TRUE   TRUE   FALSE  Unknown        Unknown   10.401316
1629   PAT_2109        SEK              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
1638    PAT_877        ACK                4   TRUE   TRUE    TRUE    False          False   15.000000
1665    PAT_433        NEV                5   TRUE  FALSE   FALSE    False           True   20.000000
1712     PAT_59        SEK                4   TRUE  FALSE   FALSE     True          False   18.000000
1980   PAT_1928        NEV              4.0   TRUE  FALSE    TRUE  Unknown        Unknown   10.401316
2160     PAT_87        SEK                4   TRUE  FALSE   FALSE    False           True   17.000000
2189   PAT_1978        SEK              5.0   TRUE   TRUE    TRUE  Unknown        Unknown   10.401316

In [ ]:


risk_df.to_csv('risk_analysis.csv', index=False)
print("Saved!")

Saved!

P I V O T  T A B L E  has started

Pivot Table Ka Matlab Kya Hota Hai?
Real life example — tumhara ghar ka budget:
Mahina  | Khana | Rent  | Travel | Total
--------|-------|-------|--------|------
January | 5000  | 10000 | 2000   | 17000
February| 4500  | 10000 | 1500   | 16000
Yeh ek pivot table hai — grouped summary!

In [42]:
risk_df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,score_changed,score_bleed,score_hurt,score_elevation,score_smoke,score_cancer_history,score_diameter_1,score_diameter_2,total_risk_score,risk_category
0,PAT_1516,1765,Unknown,Unknown,Unknown,Unknown,8,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2,PAT_1545,1867,Unknown,Unknown,Unknown,Unknown,77,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
3,PAT_1989,4061,Unknown,Unknown,Unknown,Unknown,75,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
5,PAT_1549,1882,Unknown,Unknown,Unknown,Unknown,53,Unknown,Unknown,Unknown,...,0,0,0,1,0.5,0.5,0,0,2.0,Low Risk
8,PAT_1995,4080,Unknown,Unknown,Unknown,Unknown,68,Unknown,Unknown,Unknown,...,1,0,0,0,0.5,0.5,0,0,2.0,Low Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,PAT_1407,1402,Unknown,Unknown,Unknown,Unknown,81,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2290,PAT_1294,1031,Unknown,Unknown,Unknown,Unknown,35,Unknown,Unknown,Unknown,...,0,0,1,0,0.5,0.5,0,0,2.0,Low Risk
2293,PAT_1708,3156,Unknown,Unknown,Unknown,Unknown,73,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2295,PAT_1343,1217,Unknown,Unknown,Unknown,Unknown,74,Unknown,Unknown,Unknown,...,0,0,0,0,0.5,0.5,0,0,1.0,Low Risk
2297,PAT_1714,3189,Unknown,Unknown,Unknown,Unknown,41,Unknown,Unknown,Unknown,...,0,0,0,1,0.5,0.5,0,0,3.0,Medium Risk

In [ ]:


print(risk_df['age'].describe())

count    956.000000
mean      57.041841
std       16.985437
min        6.000000
25%       46.000000
50%       59.000000
75%       69.000000
max       92.000000
Name: age, dtype: float64

In [44]:
# Hint — same tarika!
risk_df['age_group'] = pd.cut(
    risk_df['age'],
    bins=[5,20,40,60,92],
    labels=['Children/Young', 'Young Adult', 'Middle Age', 'Senior']
)

print(risk_df['age_group'].value_counts())

age_group
Senior            440
Middle Age        351
Young Adult       133
Children/Young     32
Name: count, dtype: int64

In [45]:
pivot1 = pd.pivot_table(
    risk_df,              # Kaunsa DataFrame?
    values  = 'total_risk_score',   # Z — risk score count karna hai
    index   = 'diagnostic', # X — Rows mein Diagnostic
    columns = 'risk_category',      # Y — Columns mein risk_category
    aggfunc = 'count'       # count nikalna hai         # Kya calculation? mean/sum/count
)

print(pivot1)

risk_category  Low Risk  Medium Risk  High Risk
diagnostic
ACK                 499           47          6
NEV                  75          100          9
SEK                 134           77          9

In [46]:
# Step 1 — Total column add karo
pivot1['Total'] = pivot1['Low Risk'] + pivot1['Medium Risk'] + pivot1['High Risk']

In [47]:
print(pivot1)

risk_category  Low Risk  Medium Risk  High Risk  Total
diagnostic
ACK                 499           47          6    552
NEV                  75          100          9    184
SEK                 134           77          9    220

In [48]:
# Step 2 — High Risk % add karo
pivot1['High Risk %'] = (
    pivot1['High Risk'] / pivot1['Total'] * 100
).round(2)

print(pivot1)

risk_category  Low Risk  Medium Risk  High Risk  Total  High Risk %
diagnostic
ACK                 499           47          6    552         1.09
NEV                  75          100          9    184         4.89
SEK                 134           77          9    220         4.09

NEV — normal mole — mein High Risk % sabse zyada kyun hai?
Yeh surprising hai — doctor ke liye important insight hai!


NEV Ka Nature Kya Hai?
NEV = Normal Mole — benign hai abhi!
Lekin socho —

Kya ek normal mole kabhi kabhi cancer mein badal sakta hai?

Real life mein —
Normal mole → Time ke saath → Grow kiya
                             → Color badla
                             → Bleed kiya
                             → Elevated hua
                             ⬇️
             Ab yeh suspicious lag raha hai!
             Doctor ko lagta hai — biopsy karni chahiye!


Matlab Yeh Hai
NEV wale patients mein jo Medium aur High Risk hain —
Yeh woh patients hain jinke normal mole ne alarming signs dikhane shuru kar diye!
Yeh doctor ke liye sabse important insight hai:

"NEV patients ko ignore mat karo — unhe regularly monitor karo!"

In [49]:
risk_df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,score_bleed,score_hurt,score_elevation,score_smoke,score_cancer_history,score_diameter_1,score_diameter_2,total_risk_score,risk_category,age_group
0,PAT_1516,1765,Unknown,Unknown,Unknown,Unknown,8,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Children/Young
2,PAT_1545,1867,Unknown,Unknown,Unknown,Unknown,77,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Senior
3,PAT_1989,4061,Unknown,Unknown,Unknown,Unknown,75,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Senior
5,PAT_1549,1882,Unknown,Unknown,Unknown,Unknown,53,Unknown,Unknown,Unknown,...,0,0,1,0.5,0.5,0,0,2.0,Low Risk,Middle Age
8,PAT_1995,4080,Unknown,Unknown,Unknown,Unknown,68,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,2.0,Low Risk,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,PAT_1407,1402,Unknown,Unknown,Unknown,Unknown,81,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Senior
2290,PAT_1294,1031,Unknown,Unknown,Unknown,Unknown,35,Unknown,Unknown,Unknown,...,0,1,0,0.5,0.5,0,0,2.0,Low Risk,Young Adult
2293,PAT_1708,3156,Unknown,Unknown,Unknown,Unknown,73,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Senior
2295,PAT_1343,1217,Unknown,Unknown,Unknown,Unknown,74,Unknown,Unknown,Unknown,...,0,0,0,0.5,0.5,0,0,1.0,Low Risk,Senior
2297,PAT_1714,3189,Unknown,Unknown,Unknown,Unknown,41,Unknown,Unknown,Unknown,...,0,0,1,0.5,0.5,0,0,3.0,Medium Risk,Middle Age

In [ ]:

pivot2 = pd.pivot_table(
    risk_df,
    values = 'total_risk_score',
    index  = 'diagnostic',
    columns= 'age_group',
    aggfunc= 'count'
)

pivot2['Total'] =  pivot2['Senior'] + pivot2['Middle Age'] + pivot2['Young Adult'] + pivot2['Children/Young']
pivot2['High Risk %'] = (pivot2['Senior'] / pivot2['Total']  * 100).round(2)

print(pivot2)

age_group   Children/Young  Young Adult  Middle Age  Senior  Total  \
diagnostic
ACK                    NaN         35.0       237.0   280.0    NaN
NEV                   32.0         91.0        54.0     7.0  184.0
SEK                    NaN          7.0        60.0   153.0    NaN

age_group   High Risk %
diagnostic
ACK                 NaN
NEV                 3.8
SEK                 NaN


ACK aur SEK ka Total = NaN! Something is wrong. 

ACK ka Children/Young = NaN hai!
NaN + koi bhi number = NaN! ❌
Isliye ACK aur SEK ka Total NaN aa gaya!


pehle ek doubt clear karo.
ACK ka `Children/Young` = NaN hai!   iska matlab children/young ka ek bhi value ACK nahi hai diagnostic column mei?

Yahi Matlab Hai!
ACK + Children/Young = NaN
Matlab — dataset mein ek bhi bachcha nahi hai jiska diagnostic ACK hai!

Real Life Mein Kyun?
ACK = Actinic Keratosis = Sun damage se hota hai!
Bachcha  → Kam saalon ki dhoop → ACK nahi
Senior   → 60+ saal ki dhoop  → ACK zyada!
Isliye ACK mein:

Children/Young = NaN ✅ — Logical hai!
Senior = 280 ✅ — Sabse zyada! Logical hai!

In [ ]:
# Do not aasume , always verify with the data.

ack_children = risk_df[
    (risk_df['diagnostic'] == 'ACK') & 
    (risk_df['age_group'] == 'Children/Young')
]

print("Count:", len(ack_children))

Count: 0

In [52]:
pivot2 = pd.pivot_table(
    risk_df,
    values = 'total_risk_score',
    index  = 'diagnostic',
    columns= 'age_group',
    aggfunc= 'count',
    fill_value=0
)

pivot2['Total'] =  pivot2['Senior'] + pivot2['Middle Age'] + pivot2['Young Adult'] + pivot2['Children/Young']
# pivot2['High Risk %'] = (pivot2['Senior'] / pivot2['Total']  * 100).round(2)

#pivot2['Senior %'] = (pivot2['Senior'] / pivot2['Total'] * 100).round(2)

# kyunki middle age mei cancer zyada detect hota hai
pivot2['Middle Age %'] = (pivot2['Middle Age'] / pivot2['Total'] * 100).round(2)

print(pivot2)

age_group   Children/Young  Young Adult  Middle Age  Senior  Total  \
diagnostic
ACK                      0           35         237     280    552
NEV                     32           91          54       7    184
SEK                      0            7          60     153    220

age_group   Middle Age %
diagnostic
ACK                42.93
NEV                29.35
SEK                27.27

In [53]:
with pd.ExcelWriter('skin_cancer_analysis.xlsx') as writer:
    pivot1.to_excel(writer, sheet_name='Risk by Diagnostic')
    pivot2.to_excel(writer, sheet_name='Age Group Analysis')
    risk_df.to_excel(writer, sheet_name='Full Risk Data', index=False)

print("Excel file saved!")

Excel file saved!

Task:

"Heatmap on patients data to highlight people with high risk"

Heatmap means — colors se data dikhana!
Like:
High Risk  → 🔴 Red
Medium Risk → 🟡 Yellow  
Low Risk   → 🟢 Green

In [54]:
risk_df.columns

Index(['patient_id', 'lesion_id', 'smoke', 'drink', 'background_father',
       'background_mother', 'age', 'pesticide', 'gender',
       'skin_cancer_history', 'cancer_history', 'has_piped_water',
       'has_sewage_system', 'fitspatrick', 'region', 'diameter_1',
       'diameter_2', 'diagnostic', 'itch', 'grew', 'hurt', 'changed', 'bleed',
       'elevation', 'img_id', 'biopsed', 'score_grew', 'score_changed',
       'score_bleed', 'score_hurt', 'score_elevation', 'score_smoke',
       'score_cancer_history', 'score_diameter_1', 'score_diameter_2',
       'total_risk_score', 'risk_category', 'age_group'],
      dtype='str')

In [ ]:
#Pehle columns select kiya hu:

heatmap_df = risk_df[[
    # Group 1 — Patient Info
    'patient_id', 'diagnostic', 'age_group',
    # Group 2 — Risk Summary
    'total_risk_score', 'risk_category',
    # Group 3 — Risk Factors
    'grew', 'changed', 'bleed', 'hurt', 'elevation',
    'smoke', 'cancer_history', 'diameter_1', 'diameter_2'
]].sort_values('total_risk_score', ascending=False)

#print(heatmap_df)  # 956 rows

#risk_df mein pehle se sirf biopsed=False wale hain!
#Aur heatmap_df bana hai risk_df se — toh automatically sirf False wale hain!

In [56]:
# Step 1 — Columns select karo aur score ke hisaab se sort karo
heatmap_df = risk_df[[
    'patient_id', 'diagnostic', 'age_group',
    'total_risk_score', 'risk_category',
    'grew', 'changed', 'bleed', 'hurt', 'elevation',
    'smoke', 'cancer_history', 'diameter_1', 'diameter_2'
]].sort_values('total_risk_score', ascending=False)

# Step 2 — Color function banao
def color_risk(val):
    if val == 'High Risk':
        return 'background-color: Red'
    elif val == 'Medium Risk':
        return 'background-color: Yellow'
    else:
        return 'background-color: Green'

# Step 3 — Styled object banao
styled = heatmap_df.style

# Step 4 — risk_category column mein color lagao
styled = styled.map(
    color_risk,
    subset=['risk_category']
)

# Step 5 — total_risk_score mein gradient color lagao
styled = styled.background_gradient(
    subset=['total_risk_score'],
    cmap='RdYlGn_r'
)

# Step 6 — Excel mein save karo
styled.to_excel(
    'skin_cancer_heatmap.xlsx',
    engine='openpyxl',
    index=False
)

print("Heatmap Excel saved!")

#Newer Pandas mein applymap ka naam badal gaya hai — map ho gaya!

Heatmap Excel saved!